import type { Patient } from '../domain/patient';

export const SEED_PATIENTS: Patient[] = [
  {
    id: 'PT-04821',
    name: 'Ana Torres',
    age: 34,
    email: 'ana.torres@email.com',
    phone: '+34 612 345 678',
    since: '2021-03-12',
    lastVisit: '2026-05-12',
    status: 'completed',
    history: [
      {
        id: 'c-04821-1',
        date: '2026-05-12',
        type: 'Revisión general',
        doctor: 'Dra. Elena Ruiz',
        status: 'completed',
        note: 'Revisión rutinaria sin incidencias. Constantes dentro de rango normal.',
      },
      {
        id: 'c-04821-2',
        date: '2026-02-03',
        type: 'Análisis de sangre',
        doctor: 'Dr. Andrés Vega',
        status: 'completed',
        note: 'Hemograma completo. Ligero déficit de vitamina D, se recomienda suplementación.',
      },
      {
        id: 'c-04821-3',
        date: '2025-11-20',
        type: 'Control de seguimiento',
        doctor: 'Dra. Elena Ruiz',
        status: 'completed',
        note: 'Seguimiento de tratamiento. Evolución favorable.',
      },
      {
        id: 'c-04821-4',
        date: '2025-08-09',
        type: 'Primera consulta',
        doctor: 'Dra. Elena Ruiz',
        status: 'completed',
        note: 'Anamnesis inicial. Sin antecedentes relevantes.',
      },
    ],
  },
  {
    id: 'PT-04822',
    name: 'Marco Rossi',
    age: 51,
    email: 'marco.rossi@email.com',
    phone: '+39 333 123 4567',
    since: '2019-07-22',
    lastVisit: '2026-04-28',
    status: 'pending',
    history: [
      {
        id: 'c-04822-1',
        date: '2026-04-28',
        type: 'Electrocardiograma',
        doctor: 'Dr. Marco Bianchi',
        status: 'pending',
        note: 'Pendiente de interpretación por cardiología.',
      },
      {
        id: 'c-04822-2',
        date: '2026-01-15',
        type: 'Control de seguimiento',
        doctor: 'Dr. Marco Bianchi',
        status: 'completed',
        note: 'Tensión arterial controlada con medicación actual.',
      },
      {
        id: 'c-04822-3',
        date: '2025-09-30',
        type: 'Análisis de sangre',
        doctor: 'Dr. Andrés Vega',
        status: 'completed',
        note: 'Perfil lipídico ligeramente elevado.',
      },
    ],
  },
  {
    id: 'PT-04823',
    name: 'João Lima',
    age: 27,
    email: 'joao.lima@email.com',
    phone: '+351 912 345 678',
    since: '2023-01-08',
    lastVisit: '2026-05-03',
    status: 'active',
    history: [
      {
        id: 'c-04823-1',
        date: '2026-05-03',
        type: 'Consulta dermatológica',
        doctor: 'Dra. Sofia Costa',
        status: 'active',
        note: 'En tratamiento dermatológico activo. Próxima revisión en 3 semanas.',
      },
      {
        id: 'c-04823-2',
        date: '2026-03-18',
        type: 'Primera consulta',
        doctor: 'Dra. Sofia Costa',
        status: 'completed',
        note: 'Derivado por dermatitis. Se inicia tratamiento tópico.',
      },
    ],
  },
  {
    id: 'PT-04824',
    name: 'Sofía Méndez',
    age: 42,
    email: 'sofia.mendez@email.com',
    phone: '+34 677 889 900',
    since: '2020-11-30',
    lastVisit: '2026-05-20',
    status: 'completed',
    history: [
      {
        id: 'c-04824-1',
        date: '2026-05-20',
        type: 'Vacunación',
        doctor: 'Dra. Elena Ruiz',
        status: 'completed',
        note: 'Vacuna de la gripe estacional administrada sin reacción adversa.',
      },
      {
        id: 'c-04824-2',
        date: '2026-02-28',
        type: 'Revisión general',
        doctor: 'Dra. Elena Ruiz',
        status: 'completed',
        note: 'Estado de salud general bueno.',
      },
      {
        id: 'c-04824-3',
        date: '2025-10-11',
        type: 'Análisis de sangre',
        doctor: 'Dr. Andrés Vega',
        status: 'completed',
        note: 'Resultados normales.',
      },
    ],
  },
  {
    id: 'PT-04825',
    name: 'Luca Esposito',
    age: 63,
    email: 'luca.esposito@email.com',
    phone: '+39 348 765 4321',
    since: '2018-04-17',
    lastVisit: '2026-03-30',
    status: 'cancelled',
    history: [
      {
        id: 'c-04825-1',
        date: '2026-03-30',
        type: 'Control de seguimiento',
        doctor: 'Dr. Marco Bianchi',
        status: 'cancelled',
        note: 'Cita cancelada por el paciente. Reprogramar.',
      },
      {
        id: 'c-04825-2',
        date: '2026-01-12',
        type: 'Electrocardiograma',
        doctor: 'Dr. Marco Bianchi',
        status: 'completed',
        note: 'Ritmo sinusal normal.',
      },
      {
        id: 'c-04825-3',
        date: '2025-07-05',
        type: 'Revisión general',
        doctor: 'Dra. Elena Ruiz',
        status: 'completed',
        note: 'Recomendado control de tensión periódico.',
      },
    ],
  },
  {
    id: 'PT-04826',
    name: 'Beatriz Fonseca',
    age: 38,
    email: 'beatriz.fonseca@email.com',
    phone: '+351 967 111 222',
    since: '2022-09-14',
    lastVisit: '2026-05-18',
    status: 'pending',
    history: [
      {
        id: 'c-04826-1',
        date: '2026-05-18',
        type: 'Análisis de sangre',
        doctor: 'Dr. Andrés Vega',
        status: 'pending',
        note: 'A la espera de resultados de laboratorio.',
      },
      {
        id: 'c-04826-2',
        date: '2026-02-22',
        type: 'Primera consulta',
        doctor: 'Dra. Sofia Costa',
        status: 'completed',
        note: 'Consulta inicial. Solicitada analítica de control.',
      },
    ],
  },
  {
    id: 'PT-04827',
    name: 'Daniel Ferrari',
    age: 29,
    email: 'daniel.ferrari@email.com',
    phone: '+39 320 555 7788',
    since: '2024-02-01',
    lastVisit: '2026-04-09',
    status: 'completed',
    history: [
      {
        id: 'c-04827-1',
        date: '2026-04-09',
        type: 'Revisión general',
        doctor: 'Dr. Marco Bianchi',
        status: 'completed',
        note: 'Apto para actividad deportiva. Sin contraindicaciones.',
      },
      {
        id: 'c-04827-2',
        date: '2025-12-03',
        type: 'Primera consulta',
        doctor: 'Dr. Marco Bianchi',
        status: 'completed',
        note: 'Consulta deportiva inicial.',
      },
    ],
  },
  {
    id: 'PT-04828',
    name: 'Carla Pereira',
    age: 56,
    email: 'carla.pereira@email.com',
    phone: '+351 933 444 555',
    since: '2017-06-25',
    lastVisit: '2026-05-22',
    status: 'active',
    history: [
      {
        id: 'c-04828-1',
        date: '2026-05-22',
        type: 'Control de seguimiento',
        doctor: 'Dra. Sofia Costa',
        status: 'active',
        note: 'Seguimiento crónico activo. Medicación ajustada.',
      },
      {
        id: 'c-04828-2',
        date: '2026-03-01',
        type: 'Análisis de sangre',
        doctor: 'Dr. Andrés Vega',
        status: 'completed',
        note: 'Valores estables respecto al control anterior.',
      },
      {
        id: 'c-04828-3',
        date: '2025-11-18',
        type: 'Electrocardiograma',
        doctor: 'Dr. Marco Bianchi',
        status: 'completed',
        note: 'Sin alteraciones significativas.',
      },
      {
        id: 'c-04828-4',
        date: '2025-09-02',
        type: 'Revisión general',
        doctor: 'Dra. Sofia Costa',
        status: 'completed',
        note: 'Control anual.',
      },
    ],
  },
  {
    id: 'PT-04829',
    name: 'Hugo Martín',
    age: 45,
    email: 'hugo.martin@email.com',
    phone: '+34 655 222 111',
    since: '2021-12-09',
    lastVisit: '2026-04-15',
    status: 'completed',
    history: [
      {
        id: 'c-04829-1',
        date: '2026-04-15',
        type: 'Consulta dermatológica',
        doctor: 'Dra. Sofia Costa',
        status: 'completed',
        note: 'Lesión cutánea benigna. No requiere intervención.',
      },
      {
        id: 'c-04829-2',
        date: '2025-10-28',
        type: 'Revisión general',
        doctor: 'Dra. Elena Ruiz',
        status: 'completed',
        note: 'Estado general correcto.',
      },
    ],
  },
  {
    id: 'PT-04830',
    name: 'Giulia Conti',
    age: 31,
    email: 'giulia.conti@email.com',
    phone: '+39 327 888 9900',
    since: '2023-08-19',
    lastVisit: '2026-05-25',
    status: 'pending',
    history: [
      {
        id: 'c-04830-1',
        date: '2026-05-25',
        type: 'Primera consulta',
        doctor: 'Dra. Sofia Costa',
        status: 'pending',
        note: 'Primera visita agendada. Pendiente de confirmación.',
      },
    ],
  },
];
